language: node_js

node_js:
  - "7.0"
  - "7.1"
  - "7.2"

env:
  - PATH=$HOME/purescript:$PATH

install:
  - "TAG=$(wget -q -O - https://github.com/purescript/purescript/releases/latest --server-response --max-redirect 0 2>&1 | sed -n -e 's/.*Location:.*tag\\///p')"
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - wget https://github.com/purescript/psc-package/releases/download/v0.1.1/linux64.tar.gz
  - tar xvf linux64.tar.gz
  - sudo mv psc-package/psc-package /usr/local/bin
  - sudo chmod u+x /usr/local/bin/psc-package
  - psc-package update

script:
  - psc-package build
  # - echo "Test.Unit isn't in 0.11.3!"
  # node -e "require('./output/Test.Main').main()"
